id = "taiga-theme"
name = "Taiga Theme"
version = "0.0.2"
schema_version = 1
authors = ["Josh Dales"]
description = "A theme for Zed - with light and dark modes"
repository = "https://github.com/joshdales/taiga-theme"
