id = "taiga-theme"
name = "Taiga Theme"
version = "3.0.1"
schema_version = 1
authors = ["Josh Dales"]
description = "A theme for Zed - with light and dark modes"
repository = "https://github.com/joshdales/taiga-vs-code-theme"
