name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version to release"
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Setup git config
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    - name: Publish new version
      run: |
        npm install
        npm run publish ${{ github.event.inputs.release_version }} -p ${{ secrets.access_token }}
        git push
