name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of version to release"
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
env:
  PACKAGE_NAME: taiga-theme.vsix
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.ACCESS_TOKEN }}
      OVSX_PAT: ${{ secrets.OPEN_VSX_PAT }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Package extension
      run: |
        npm install
        npm run package ${{ github.event.inputs.release_type }}
        git push
    - name: Publish to VSCode Marketplace
      run: npm run publish:vsce
    - name: Publish to Open VSX Registry
      run: npm run publish:ovsx
    - name: Set version output
      run: echo "VERSION=v$(npm pkg get version | tr -d \")" >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_NAME }}
  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          VERSION: ${{ needs.publish.outputs.VERSION }}
        run: gh release create $VERSION $PACKAGE_NAME --generate-notes
