name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version to release"
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.access_token }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-node@v4
    - name: Publish extension to VSCode Marketplace
      run: |
        npm install
        npm run publish ${{ github.event.inputs.release_version }}
        git push
