name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of version to release"
        required: true
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.ACCESS_TOKEN }}
      OVSX_PAT: ${{ secrets.OPEN_VSX_PAT }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Package extension
      run: |
        npm install
        npm run package ${{ github.event.inputs.release_type }}
        git push
    - name: Publish to VSCode Marketplace
      run: npm run publish:vsce
    - name: Publish to Open VSX Registry
      run: npm run publish:ovsx
